#Variables
a = 5
b = 6
c = a+b
print (c)

#Variables con string
nombre = "D4rk1"
print (nombre)

#Variables con numeros y suma 
numero = 10
numero += 10
numero -= 5
print (numero)

#Concatenacion de letras
bienvenida = "Hola "
nombre1 = "Lucas "
nombre = bienvenida + nombre1 + "¿Como estas?"
print (nombre)

#Concatenacion con Fstring
bienvenida = "Hola "
nombre1 = 5
nombre = f"{bienvenida} {nombre1} ¿Como estas?"
print (nombre)


#Definiendo con snake_case
name_name = "Reiko"
#Definiendo con camelCase
nameName = "Reiko"
 